pipeline {
  agent any
  stages {
    stage (‘Build’) {
      steps {
        sh "mvn clean package" 
        } } 
  stage (‘Deploy’) {
    steps {
      script {
        deploy adapters: [tomcat9(credentialsId: "8b7c4956-b765-42ef-b1ee-055bb8557ed9", path: ‘’, url: "http://localhost:8083")], contextPath: "/pipeline", onFailure: false, war: "target/*.war"
        } 
      } 
    }
  } 
 }
