pipeline {
  /*agent any tools{ 
    maven ‘maven-3.8.6’ 
    }*/   
  stages {
    stage (‘Build’) {
      steps {
        sh ‘mvn clean package’ 
        } } 
  stage (‘Deploy’) {
    steps {
      script {
        deploy adapters: [tomcat9(credentialsId: ‘tomcat_credential’, path: ‘’, url: "http://localhost:8083")], contextPath: ‘/pipeline’, onFailure: false, war: ‘target/*.war’ 
        } 
      } 
    }
  } 
 }
